package aws

import (
	"errors"
	"fmt"
	"time"

	"github.com/Trivenqo/GhostKey/internal/connector/sdk"
	"github.com/Trivenqo/GhostKey/internal/shared/canonical"
)

type Normalizer struct{}

func NewNormalizer() *Normalizer {
	return &Normalizer{}
}

// Normalize safely extracts fields from the raw AWS JSON map.
func (n *Normalizer) Normalize(raw sdk.RawRecord) (canonical.Identity, error) {
	resourceType, ok := raw["resource_type"].(string)
	if !ok {
		return canonical.Identity{}, errors.New("missing or invalid resource_type")
	}

	arn, _ := raw["arn"].(string)
	if arn == "" {
		return canonical.Identity{}, errors.New("missing ARN")
	}

	createDateStr, _ := raw["create_date"].(string)
	createDate, _ := time.Parse(time.RFC3339, createDateStr)

	identity := canonical.Identity{
		ID:          fmt.Sprintf("id_%s", arn), // In real implementation, UUID generated by domain
		ExternalRef: canonical.ProviderRef{
			Provider:   "aws",
			ExternalID: arn,
			// AccountRef would be parsed from ARN in a real implementation
			AccountRef: "unknown", 
		},
		CreatedAt:   createDate,
		Metadata:    make(map[string]string),
	}

	// Extract Tags into Metadata safely
	if tags, ok := raw["tags"].(map[string]interface{}); ok {
		for k, v := range tags {
			if strVal, ok := v.(string); ok {
				identity.Metadata[k] = strVal
			}
		}
	}

	// Type-specific extraction
	switch resourceType {
	case "iam_user":
		identity.Type = canonical.IdentityTypeServiceAccount
		identity.DisplayName, _ = raw["user_name"].(string)
		
	case "iam_role":
		identity.Type = canonical.IdentityTypeIAMRole
		identity.DisplayName, _ = raw["role_name"].(string)
		
	default:
		return canonical.Identity{}, fmt.Errorf("unsupported AWS resource type: %s", resourceType)
	}

	return identity, nil
}