FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o migrate_bin ./cmd/migrate

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/migrate_bin .
# We must copy the SQL files so the binary can find them!
COPY migrations/ ./migrations/
CMD ["./migrate_bin"]